# Generated by Django 5.2 on 2025-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="mentioned_users",
            field=models.JSONField(default=list),
        ),
    ]
